### ISSUE TITLE
Need to choose a word that describes different views of the same resource

### ISSUE THREAD

**Issue by jkreft-usgs** [opengeospatial/SELFIE#1]
I have a resource, and want to be able to share information about it in a variety of different ways.  

- Representation is a tough word to deal with. Semantics of the word representation is different with different context.
- Maybe: if we can leave it to content negotiation then it is a different "format" of the same thing. If there is more semantic distinction than can be handled by content negotiation, then it is a different representation. 
- What's a better word? DXWG has "profile" vs "mediatype" rather than "representation" vs "format".
-- profile
-- representation
-- model
-- view

At the end of the day we will have this distinction of profile and media type -- we will explore how to use it on an info page. Having a standard list of "profiles" is a good goal that we may be able to illustrate the (potential) value of.

**Comment by dblodgett-usgs** [comment]
Defer to work on a context for the set of dimensions we want to describe information resource URIs.
