### ISSUE TITLE
Interest in schema.org developments for research data

### ISSUE THREAD

**Issue by mattfry-ceh** [opengeospatial/SELFIE#10]
There was a discussion in a previous SELFIE telecon about use of schema.org representations to enable harvesting of links to resources for environmental features to enable automated building of networks of related features.

Is this something that the group wants to pursue, or out of scope for now?

I mention it as there's an RDA working group being set up to look at schema.org metadata for research datasets. https://rd-alliance.org/groups/research-schemas-wg

It's currently running monthly meetings to define the scope of this working group, so now could be the time to get involved. They are planning to officially start this activity in October following the current scoping, and "Propose data model and data types for research schemas" in April - Oct. 2020. We have a mechanism, in the RDA Global Water group, for feeding in requirements, though people can just contribute directly of course.

**Comment by sgrellet** [comment]
Thanks Matt for the info
From my side this is something important to start investigating (thus, the proposal in our slides). Then , it's also a question of who else in SELFIE is interesting working on that piece of SELFIE puzzle. Would you be interested from CEH side ?

**Comment by dblodgett-usgs** [comment]
@mattfry-ceh what do you mean by  
> "schema.org representations"  
?

Side note, we are going to hear from folks working on this: https://github.com/ESIPFed/science-on-schema.org on the next telecon.

**Comment by mattfry-ceh** [comment]
I knew I wouldn't get away with using that word...


I mean some schema.org format info about the thing we want to be discovered.


But I will defer to the ESIP definition.

________________________________

**Comment by dblodgett-usgs** [comment]
That's basically what I thought you meant. Much of what we did in ELFIE was focused on how to use existing schema.org semantics for environmental features. But it seems that they are open to onboarding additions -- which we could maybe suggest based on things like sosa and geosparql?

**Comment by mattfry-ceh** [comment]
Yes. I would like to be able to harvest (or search for) features that have been declared to be linked to my river network and that have measurements. Rather than finding all monitoring features and having to do some terrible GIS analysis to work out if they are anything to do with the river or not.


Too specific?


I guess it's this spatial relationship that we (I) would like to get on there (or at least see if it's possible without getting too messy), so it might be making them (this working group) aware of that early on, and that we have a use case.

________________________________

**Comment by dblodgett-usgs** [comment]
I think it makes good sense. Probably a good topic to discuss on the next call -- "is there a topological contribution in the works or that could be made to schema.org?"

**Comment by bsimons14** [comment]
I understand that the Australian (CSIRO, Geoscience Australia, ABS) Loc-L project is looking at formalising spatial relationships (extending from FSDF work). Is this the case Will Francis?

**Comment by dblodgett-usgs** [comment]
Going to close this -- will open up more specific one to look at schema.org usage.
