### ISSUE TITLE
OWL Time Name Space?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#106]
Should the namespace `time` in https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-network.jsonld be: `https://www.w3.org/TR/owl-time/#time:` ? 

I'm looking at: https://www.w3.org/TR/owl-time/#time:after and if we want aliases to be like `time:after` then wouldn't the namespace in the context need to be: `https://www.w3.org/TR/owl-time/#time:` ?

**Comment by dr-shorthair** [comment]
The OWL-Time namespace is http://www.w3.org/2006/time#

**Comment by dr-shorthair** [comment]
https://www.w3.org/TR/owl-time/ is the URI for the _specification_, not the RDF namespace

**Comment by dblodgett-usgs** [comment]
Thanks. There was a mistake in the context... although what you get at the spec is way more useful. Fixed here now: https://github.com/opengeospatial/ELFIE/blob/master/docs/contexts/elfie-2/elf-network.jsonld

**Comment by dr-shorthair** [comment]
Note, however, that if you want the temporal aggregates, you need to load this graph: https://raw.githubusercontent.com/w3c/sdw/gh-pages/time-aggregates/rdf/time-agg.ttl 
(same namespace, more features, imports the original)
