### ISSUE TITLE
Flesh out definitions from face to face notes.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#14]
Note that initial definitions are here: https://opengeospatial.github.io/SELFIE/SELFIE_activity_plan#definitions

Maybe grab that and start an ER section of definitions?

From notes:
Define some of the specific words we are using in the architecture in a glossary -- provide illustrative examples and similar terminology.

**Comment by dblodgett-usgs** [comment]
_node, hub, provider, resolver_
I want to propose that the term _node_ is meant to be general and the terms _resolver_, _hub_ and _provider_ are more specific. So we could say _provider nodes_ are sources of data to _hub nodes_. And that _resolver nodes_ maintain ID -> Info redirection to _hub nodes_. Extending this, a _hub node_ can be a _resolver_ and a _provider_.

**Comment by dblodgett-usgs** [comment]
Opened #27 to work on this. Some others I'm thinking about...
resolver, hub, node, provider... others?

**Comment by dblodgett-usgs** [comment]
@abhritchie is planning on reviewing various reference docs and double checking / adding things here: https://github.com/opengeospatial/SELFIE/blob/master/docs/definitions.md

**Comment by abhritchie** [comment]
URI RFC: https://tools.ietf.org/html/rfc3986
RDF Primer: https://www.w3.org/TR/2014/NOTE-rdf11-primer-20140624/
