### ISSUE TITLE
Document general SELFIE architecture per face to face notes.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#15]
Will be a basic architecture diagram with a few sentence caption in google-draw format.

**Comment by dblodgett-usgs** [comment]
See: https://docs.google.com/drawings/d/1K63ogV1W5x1nQQGrD_o2MUL0bJDF8F4TkfruKMWW73g/edit for a draft. @abhritchie What do you think?

**Comment by alpha-beta-soup** [comment]
I added the `conneg` and `subjectOf`, `about`, `rdfs:type` and `dct:type` annotations to the diagram according to my understanding. Correct if misapplied.

**Comment by alpha-beta-soup** [comment]
I added the `<link rel="canonical">` annotation too. (I'm still not 100% clear on how this relationship is established in JSON-LD: is it the value of the `@id` property for the MIR?) For the HTML MIR landing page, that canonical `link` is a key part of the architecture that ensures that search engines index correctly despite being redirected.

**Comment by dblodgett-usgs** [comment]
Generally looks good. We need to come to conclusion on whether we are going to use the rdfs:type and dct:type distinction in there -- I think the answer is no. @abhritchie is going to be working through some examples over in #29 for later discussion. I expect this will be a primary topic of our upcoming telecon.

**Comment by dblodgett-usgs** [comment]
Going to call this one done for now and we'll come back to it in conversation.
