### ISSUE TITLE
Testing plan for relating NIRs and IRs

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#19]
We need to flesh out the considerations and issues related to the relationship between non-information-resources (NIRs) and information resources (IRs). 

This includes things like:  
1. what do search engines do with NIRs when they get a 303 to an IR at a different URL? This query indicates they index the NIR. https://www.google.com/search?q=Richelieu+aquifer
1. What happens when people use the IR URL as an ID for the NIR and things get mixed up? Proposal is to just say that the IR and NIR are owl:sameAs so they get interpreted as the same thing.
1. What happens when they _are_ the same URL because the same group minted the ID and maintain the index about that ID and don't want to have the complexity of an NIR redirect?
1. Add other considerations as this gets fleshed out.

**Comment by alpha-beta-soup** [comment]
Perhaps the data at the IR URI should establish that `NIR URI rdfs:isDefinedBy <IR URI>`? That's an explicit example here: https://www.w3.org/TR/cooluris/#linking

`rdfs:isDefinedBy` is a subclass of `rdfs:sameAs`; but `rdfs:sameAs` seems too symmetrical and too weak.

**Comment by abhritchie** [comment]
Actually, owl:sameAs is very strong and does exactly what we want it to do: thing 1 is the same as thing 2 and all statements made about thing 1 also apply to thing 2 and vice versa.

**Comment by abhritchie** [comment]
I think we might be missing the obvious here too. With the specific example that kicked this issue off, dereferencing the NIR URI and getting an 'info page' IR back the @id value in the JSONLD returned or embedded in the response should be the URI of the NIR, therefore the same as the owl:sameAs we are proposing.
Recall the info page is a convenience resource to support search engine indexing and present paths to related 'data' resources. It's not a (owl:) thing in its own right.

**Comment by abhritchie** [comment]
I think SIRF is on the right track by treating the alternates page (equiv to the info page) as a view of the NIR.

**Comment by jvanulde** [comment]
I'm leaning towards using `rdfs:isDefinedBy` rather than `rdfs:sameAs` as @alpha-beta-soup suggested. The problem with overloading `rdfs:sameAs` to describe the relation between a NIR and IR is that a consumer (e.g. harvester) can't discern between an actual relation between resources and a NIR/IR relation.

**Comment by abhritchie** [comment]
Fair call WRT use of sameAs - getting a bit caught up with Boyan's suggestion in the original conversation that triggered this issue and its focus on the info page.
For NIR to IR rdfs:isDefinedBy is good (note, though, that it is a subproperty of rdfs:seeAlso, not owl:sameAs), but ... said it a few times now but the idea of an IR is too broad. We have at least two types of IR, the 'info' IR (IIR) and 'data' IR (DIR).
NIR rdfs:isDefinedBy DIR - makes sense and I image the RDF in an IIR would contain these triples
NIR rdfs:isDefinedBy IIR - I need convincing the info page/resource is a definitive resource

**Comment by dblodgett-usgs** [comment]
Based on conversation in Quebec City -- we concluded that whether we use 303 redirects between NIRs and MIRs doesn't make much of a difference. We will recommend keeping conceptual separation (separate URIs) between the NIR and the MIR and plan on testing the case where there is no separation. 

We will recognize the issues inherent in indirect identification (same URI) and recommend that the two URIs are distinct.

The second issue -- what should a reasoner do in relation to the NIR when it encounters the MIR URI? Should we publish a set of owl:sameAs relations between our NIRs and MIRs? -- no. We will not implement the sameAs relation or any other relation to relate the NIR and MIR.

This should be a consideration for the HTML version of the MIR. #16 is relevant here.

**Comment by dblodgett-usgs** [comment]
This issue can be closed when the above conclusion has been drafted into engineering report form.

**Comment by dblodgett-usgs** [comment]
How's this read?

> The SELFIE resource model, with its non-information, meta-information, and data tiers, is focused on the nature of the resource and not the structure of the identifier used to dereference the resource. However, there is a need to establish expected behavior when dereferencing URLs for information at each of these three tiers. The SELFIE project tested two behaviors between NIR and MIR:
> 
> 1. A 303 redirect from a URL for a NIR to the URL for an MIR 
> 1. Indirect identification of the NIR with the URL that locates an MIR with a 200 response code. 
> 
> The distinction between a NIRs and MIRs located with different URLs introduces the potential for confusion. Indexes of MIR content might get associated with the MIR URL rather than an NIR URL the MIR documents. MIR URLs might get used as NIRs because of accidental use of the URL returned by the 303 redirect. SELFIE has tested the former by exposing pilot infrastructure to the public internet and found that, as long as statements in the MIR reference the NIR URL, search engines and indexers will work appropriately. The second issue can be mitigated by placing prominent NIR URLs on the html representation of an MIR page and structure MIR URLs in such a way that it is clear that they are not meant to be used as identifiers.
> 
> Indirect identification of NIRs using MIR URLs has been tested by SELFIE participants successfully. It was found that this practice limits flexibility of systems to accommodate multiple agencies and the tight coupling of NIR to MIR introduces technical challenges for MIR resolution. However, the practice is less complicated from a user perspective and, as long as the NIR URLs are stable, is compatible with future decoupling of NIR and MIR URLs when the separation is needed. These two cases, 303 and 200 response codes to a NIR URL, illustrate the flexibility of the SELFIE resource model as well as the nature of an MIR as a convenient resource that encodes a set of statements relating NIRs to each other and data resources. 
>

**Comment by jvanulde** [comment]
> Based on conversation in Quebec City -- we concluded that whether we use 303 redirects between NIRs and MIRs doesn't make much of a difference. We will recommend keeping conceptual separation (separate URIs) between the NIR and the MIR and plan on testing the case where there is no separation.
> 
> We will recognize the issues inherent in indirect identification (same URI) and recommend that the two URIs are distinct.
> 
> The second issue -- what should a reasoner do in relation to the NIR when it encounters the MIR URI? Should we publish a set of owl:sameAs relations between our NIRs and MIRs? -- no. We will not implement the sameAs relation or any other relation to relate the NIR and MIR.
> 
> This should be a consideration for the HTML version of the MIR. #16 is relevant here.

I recall that we discussed using an `about` relation to link the MIR to the NIR...

**Comment by dblodgett-usgs** [comment]
Since about is the inverse of `schema:subjectOf`, I guess we would just add the MR URL to the `schema:subjectOf` set of relations? Going to put that in the example after discussion with @abhritchie

**Comment by dblodgett-usgs** [comment]
Just copied and rewrote the text in this issue here. https://docs.google.com/document/d/1b-TdqWl3jf2jJD7dYvLkxTa6JEGxtUJAue7jSiaEE2s/edit#bookmark=id.hc1p9qsw7zga
