### ISSUE TITLE
Build example of a timeseries as a representation of a monitoring site.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#22]
As discussed in Leuven, one approach to linking observational data to a site is through a simple "seeAlso" relation to a time series or water quality result for a monitoring location. This seems like a reasonable first approximation of the relationship and is interpretable especially if the timeseries URL is documented including it's data type in addition to media type. 

@jvanulde and @denevers -- do you have an example of this in GSIP already? I don't, but could add a number of them pretty easily. I already have some sites listed like: https://cida-test.er.usgs.gov/chyld-pilot/id/gage/04282525 that link to the NWIS site page but don't have actual data linked directly.

**Comment by denevers** [comment]
I think there is confusion here.  The seeAlso (and this property name is debatable) is to link a NIR to a IR in the info page. I think the essence of the discussion was - how one gets to time series data using the info page and the answer was . the info page will get you to the monitoring station (or well, or whatever) and one of the representation (IR)  - identified by seeAlso - may or may not contain a time series.

*BUT* if the timeseries becomes a "first class citizen", it becomes its own NIR, a link will exist, based on the ontology we choose.  We will most probably have both cases: timeseries as NIR or as part of one of the representation.  

This will be fun to untangle...

**Comment by dblodgett-usgs** [comment]
No confusion on my part. I am also thinking about implementing what GSIP has -- a site as an NIR that has a timeseries as a linked IR. So we already have an example of this. Good! https://github.com/opengeospatial/SELFIE/issues/23 is to work on the idea that an observation could be an NIR in its own right.

**Comment by bsimons14** [comment]
Although Observation is a feature in its own right I think giving it its own NIR id as opposed to just using the SpatialSamplingFeature that generated it is likely to lead to confusion.
Is there a good use case for Observations to be treated as NIRs?

**Comment by dblodgett-usgs** [comment]
I could see doing it for observations with a complex result that is an ongoing timeseries at a particular site, but I think I agree, we probably don't want to go there. Let's take the discussion to #23
