### ISSUE TITLE
Mock up info page for an observation as a feature.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#23]
Flesh out an info page for an observation to explore the idea of an observation as a feature in the SELFIE resource model. -- feeds the O&M SWG and how to work with sensorthings.

Pull Kathi into this as well? Don't have her on github.

**Comment by hylkevds** [comment]
@KathiSchleidt is now pulled into this :)

**Comment by bsimons14** [comment]
Although Observation is a feature in its own right I think giving it its own NIR id as opposed to just using the SpatialSamplingFeature that generated it is likely to lead to confusion.
Is there a good use case for Observations to be treated as NIRs?

**Comment by dblodgett-usgs** [comment]
With our current paradigm, I'm not really seeing how we will deal with observations without putting some fairly complex linked data in a sampling feature info resource. If we do that, we would follow this example: https://opengeospatial.github.io/ELFIE/FR/HydroStation/sgwlf/U124404001 and our info resources would need to have a sampling section separate from the representations section? 

I could see changing this issue to go that direction. What do others think?

**Comment by abhritchie** [comment]
Need clarity of what is meant by an observation being a feature in the SELFIE resource model. The SELFIE resource model is a meta model helping us defining behaviour of useful web representations of NIRs and IRs: info page etc. An observation is a feature below (alongside?) this meta level, a domain feature - we need to keep them seperate.

Certain types of bservations may sensibly be always returned inline within a sampling feature, but other types may be better provided as links. Accordingly, the results may be linked (coverage, timeseries).

For a given observation type need to be defining a set of patterns and when to use them, e.g. (-> is a link, + is inline ->/+ is a choice):
sampling feature -> observation + result (simple observation, e.g. pH)
sampling feature -> observation +/-> result**s** (complex observation, e.g. multiple analytes from an XRF)
sampling feature -> observation collection -> result (timeseries observation)
sampling feature -> observation collection + results (timeseries observation - filtered subset, e.g. SOS result)

Another question is what would a link to an observation look like. Standard ELFIE? @id, @type, name or something different? @id, @type, observedProperty.

**Comment by dblodgett-usgs** [comment]
For SELFIE, we decided that we will link observation results directly to sampling features using a limited application of SOSA as tested in ELFIE-1. For this, we will more or less work from this example: https://opengeospatial.github.io/ELFIE/mwnz/sosa-sample-2108.json 

We will treat services that provide results much the same as we are doing for representations of features with subjectOf relations. That is, like the examples here: https://github.com/opengeospatial/SELFIE/blob/master/docs/examples/meta-resource.jsonld#L97 only nested under a is FeatureOfInterest > Result relation. This will allow us to link directly to (default) timeseries result API requests in the MR using existing work that was done on ELFIE as the basis.

**Comment by bsimons14** [comment]
The examples here appear to represent a single Observation in the MetaResource. I feel this would bloat the MR when there are multiple Observations on the same NIR. I would like to be able to include ssn-ext:ObservationCollection (I think) in "subjectOf" to reference all the observations, as provided by a separate ObservationCollection service.
For example:
"subjectOf": [
		{
			"url": "URI for the collection of observations related to the NRI",
			"dctType": "ssn-ext:ObservationCollection",
			"format": [
				"application/ld+json",
				"application/xml"
			],
			"conformsTo": "http://www.w3.org/ns/ssn/ext/",
			"provider": "https://www.cerdi.edu.au"
		},
However, I'm not convinced that the ObservationCollection itself should have its own MR.

**Comment by KathiSchleidt** [comment]
As Bruce pointed out, providing ALL observations on a FoI could lead to serious overload!

I can't find ssn-ext:ObservationCollection - is this burried somewhere in the ongoing work, or a confusion with the oboe:ObservationCollection referenced in https://www.w3.org/TR/vocab-ssn/#OBOE_Alignment_class?
I do think that such a collection would be most valuable, whereby I'm trying to understand if this collection is 
1. all of one type (same FoI (or Ufo), ObsProp and Process)
2. a larger collection of observations across concepts (i.e. a STA endpoint)
Once we know what the collection is, we can discuss if it has a MR

Also - I'm wondering if the "potential observation" we came up with in INSPIRE (Observing Capabilities in INSPIRE Speak) could be a useful buffer between our real world things and the pile of observations upon them, with the potential observation providing information on its source (service). I've added this to the O&M CRs: http://ogc.standardstracker.org/show_request.cgi?id=575

I'm getting the impression that we're conflating conceptual and physical levels here. Think we're all agreed on conceptual/logical linkages, this is more to do with the profile/facet/view stuff - what is physically provided to a user requesting a certain resource in a certain manner.

A further clarification - to my memory this is also about pulling data together from multiple sources. Is the assumption that all data will be known to the FoI still valid. (this would be an argument for version 2 in my collection options, I can see keeping track of what organizations serve data on a resource, but not keeping track of all observation types they may have on this resource)

I'm also wondering if we aren't talking about 2 "flavours" of observations here:
1. Observations integrally important for the understanding of the FoI (so a type of complex property). In some cases, this could also be the more recent measurement of a time series (i.e. current depth)
2. Observations made on the FoI (our usual measurements or time series)
Observations of flavour 1 could be provided together with the FoI thingy, observations of flavour 2 should be provided separately (or upon explicit request, either a specific profile/facet/view, or expand functionality (STA allows you to tell the service what all to nest))

**Comment by bsimons14** [comment]
The ssn-ext:ObservationCollection is described at:
https://w3c.github.io/sdw/proposals/ssn-extensions/#sosa:ObservationCollection
Discussion on what it should contain is at:
https://github.com/w3c/sdw-sosa-ssn/issues/12
Upshot is that it should have at least one of the following in common:
- feature-of-interest
- ultimate feature-of-interest
- observed-property
- procedure
- sensor
- phenomenon-time
- result-time

**Comment by KathiSchleidt** [comment]
I've ruminated further, but as I need pictures to think, I've outsourced this bit to a google doc (sorry, can't shake my graphics background). Please provide feedback to the text at:
https://docs.google.com/document/d/1ET8sjEeuT9ytdckmD85_HFSowWeIus8giUsglO0AUI8/edit?usp=sharing

**Comment by bsimons14** [comment]
I have posted 'data resource' examples of ObservationCollection (https://github.com/opengeospatial/SELFIE/blob/master/docs/examples/ObservationCollection.jsonld) and Observation (https://github.com/opengeospatial/SELFIE/blob/master/docs/examples/Observation.jsonld). Although some of the formatting is wrong (I'm still unclear on transforming rdf to json), I think the combination of ObservationCollection and Observation resources, both using the NIR ID as the 'about' property,  will meet all FedUnis requirements to deliver observation results about a NIR.

**Comment by KathiSchleidt** [comment]
Think I've got the observation sorted, had to add some context files.
I first sorted @bsimons14 example to the point where it's valid JSON-LD, then made a copy under Observation_KS where I did the detailed fixes. Awaiting a pull request
I'll look at the collection over the weekend

**Comment by dblodgett-usgs** [comment]
We've done plenty on this issue and should spin up a new issue to write up the findings. In the interest of focusing our efforts I'm going to close this and we can take it up in w3c/sdw#40 and the ER.
