### ISSUE TITLE
Complete analysis of "authority" tags for datasets.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#26]
For owner / authority
check what best to convey “owner”. 
https://www.w3.org/TR/vocab-dcat-2/#examples-dataset-provenance
Check PROVO prov:generatedBy
https://schema.org/provider 
https://schema.org/sourceOrganization

Outcome should be a few paragraphs for engineering report.

**Comment by dblodgett-usgs** [comment]
@abhritchie -- I'm happy with: https://schema.org/provider Was there further discussion of this in QC? It seems like this is a good lowest common denominator for what we mean?

https://github.com/opengeospatial/SELFIE/blob/master/docs/contexts/elf-data.jsonld#L7

**Comment by abhritchie** [comment]
Yep, this was discussed and accepted. Of the options we decided on schema:provider applying the 'if schema.org has a property we can use then we use it' guide.
