### ISSUE TITLE
Data resource representation in meta-resource.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#29]
The examples here: https://github.com/opengeospatial/SELFIE/tree/master/docs/examples document two ways of dealing with data resources and link to them from the meta-resource. 

@abhritchie is testing both so we can demonstrate and communicate why one is preferable to the other.

Close this issue once the demonstration and documentation of which is preferable is complete.

**Comment by bsimons14** [comment]
I suggest adding 'schema:report' to the elf-index.jsonld context file to allow links to published reports on the feature.
I'm new to this json caper, is it:
"report": {
            "@id": "schema:report",
            "@type": "@id"
        },

**Comment by bsimons14** [comment]
In addition to the spatial geometry (I assume "polygon": "schema:polygon", handles point data?) I would like to see gwml:shape and/or gsml:shape available for the MIR.

**Comment by abhritchie** [comment]
Thanks @bsimons14 . It would be: "report": "schema:report" (in our way of doing contexts).

**Comment by abhritchie** [comment]
No, of course schema:polygon doesn't handle point data. The contexts are a work in progress and we'll need to add more to them as we go. As for adding g(w|s)ml:shape ... let's discuss this after tomorrow's meeting where we show what has been baked out of the Quebec and Tacoma discussions.
Although, technically, the answer is: put whatever you want in your documents - we are working to the open world assumption so there are no restrictions. Instead, with the schema.org properties, we are strongly encouraging the use of a set of them to aid indexing by search engines.

**Comment by dblodgett-usgs** [comment]
Going to close this stale issue in favor of #43 and other future work.
