### ISSUE TITLE
Devise strategy for longer term preservation and retention of SELFIE artifacts as LOD

### ISSUE THREAD

**Issue by lewismc** [opengeospatial/SELFIE#3]
Towards the end of today's telecon (which touched on some really interesting material) I got thinking about how the group preserves anything which represents an environmental linked feature(s) (ELF) as Linked Open Data (LOD).

An HTML Website pointing to the resources such as JSON-LD contexts and content instantiation examples was made available at https://opengeospatial.github.io/ELFIE/json-ld/ but what is not clear is whether these resources (such as the namespace IRIs) are permanent or not!

I want to keep this issue description as simple as possible  so I'll leave it there for now. My feeling is that putting an early vision in place would address this concern and would could resolve this issue quickly and just reference it later on.

**Comment by lewismc** [comment]
Any comments here folks?

**Comment by dblodgett-usgs** [comment]
In ELFIE, we didn't intend for anything to be strictly permanent. I think we will seek out more permanent solutions in SELFIE but also don't think we should let issues related to long-term viability of these outcomes hold us back. That make sense?

**Comment by abhritchie** [comment]
Yes, the ELFIEs are very much an experiment and the resources in question aren't really up to publication standard. But, those contexts were created and published the way they were to prove the value of enduring, shared contexts and I think ELFIE-1 succeeded. My tentative vision is a spin off of ELFIE that establishes an _LOD profile of WFS 3.0_. This has two essential components:
1. GML application schema published as ontologies (for the contexts to point to)
1. Published 'canonical' contexts with a persistent IRI (by the OGC-NA)
I'm not sure how this would be done in the OGC structure (an LOD profile of WFS 3.0 SWG?) but we should get it established before the completion of SELFIE.

**Comment by lewismc** [comment]
@dblodgett-usgs yes makes sense.
