### ISSUE TITLE
lab.scinfo.org.nz LD+OGC API - Features demo

### ISSUE THREAD

**Issue by abhritchie** [opengeospatial/SELFIE#30]
Create a SELFIE demo using Linked Data and OGC API - Features interfaces. Based on discussions at ESIP with @dblodgett-usgs and Doug Fils (@fils).

**Tools**
- [github.io](https://opengeospatial.github.io/SELFIE/examples/) - file store
- [Auscope PID service](https://confluence.csiro.au/pages/viewpage.action?pageId=436900853) - uri dereferencing/conneg
- [PyGeoAPI](https://github.com/geopython/pygeoapi) - OGC API - Features
- [JSON-LD Playground](https://json-ld.org/playground/) - testing/validation
- [GeoJSONLint](http://geojsonlint.com/) - testing/validation
- [Easy RDF Converter](http://www.easyrdf.org/converter) - JSON-LD -> TTL
- [JSON Schema Tool](https://jsonschema.net/) - generate JSON Schema
- [JSON Editor](https://json-editor.github.io/json-editor/) - Q&D test JSON-LD documents

**Plan**
1. Create JSON-LD and TTl files (github.io)  **DONE**
1. Create GeoJSON-LD **DONE**
1. Config PID - 303 redirects to github.io **DONE**
1. Deploy PyGeoAPI (lab.scinfo.org.nz/selfie/api/) and load GeoJSON-LD from 2 **DONE**
1. Test

**Demo**
1. URI (geojson conneg) -> PyGeoAPI -> response -> JSON-LD playground -> RDF
2. URI (geojson conneg) -> JSON Schema -> schema -> JSON Editor -> result -> JSON-LD playground

**Comment by abhritchie** [comment]
![image](https://user-images.githubusercontent.com/9596562/61582729-a0992500-ab82-11e9-9762-4f892044c9ea.png)

**Comment by abhritchie** [comment]
Background material (courtesy Doug Fils):
- https://github.com/earthcubearchitecture-project418/p418Docs/blob/master/publishing.md#developing-a-workflow-for-non-technical-authors
- https://github.com/geoschemas-org/geoshapes/blob/master/shapegraphs/googleRequired.ttl (not in scope but cool)

**Comment by abhritchie** [comment]
Background reading (courtesy @fils):
- https://github.com/earthcubearchitecture-project418/p418Docs/blob/master/publishing.md#developing-a-workflow-for-non-technical-authors
- https://github.com/geoschemas-org/geoshapes/blob/master/shapegraphs/googleRequired.ttl (not in scope but cool)

**Comment by abhritchie** [comment]
Files created in docs/examples and docs/examples/rdf.
PID Service configured to resolve https://lab.scinfo.org.nz/selfie URIs (with conneg, including the f query parameter override).
*Needs testing!*

**Comment by dblodgett-usgs** [comment]
You are going to have to demo this stuff on the call next week.

**Comment by abhritchie** [comment]
Will do. API should be up and running later today (if I stay awake, got home a few hours ago). Then some testing.

________________________________

**Comment by dblodgett-usgs** [comment]
@abhritchie and @alpha-beta-soup -- AFAIC this issue is complete and we should open a new one for modifications to this content rather than leaving this linger. Are you ok with that?
