### ISSUE TITLE
Data Resource representation - Quebec discussion clarification (?)

### ISSUE THREAD

**Issue by denevers** [opengeospatial/SELFIE#33]
Discussion over the rationale of the issue described #29 

Here’s my understanding of the problem @abhritchie identified in Quebec.  Please confirm / infirm

When a NIR is dereferenced, a MIR document provides a series of representations with each their own identity. GSIP has a mechanism to hide complex access point (often API) under a GSIP “data” URI

eg:

https://geoconnex.ca/id/catchment/02OJ*AB returns this MIR (just the relevant bits)

```
@prefix dct: <http://purl.org/dc/terms/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<https://geoconnex.ca/id/catchment/02OJ*AB>
rdfs:seeAlso <https://geoconnex.ca/data/catchment/HYF/WSCSSSDA/NRCAN/02OJ*AB>.

<https://geoconnex.ca/data/catchment/HYF/WSCSSSDA/NRCAN/02OJ*AB>
dct:format "application/vnd.geo+json" , "text/html" .

```

First triple tells that the NIR has a DIR encoded using a GSIP convenience URL for a representation (`<https://geoconnex.ca/data/catchment/HYF/WSCSSSDA/NRCAN/02OJ*AB>`) and the second triple tells that this representation has 2 formats.

Once someone dereferences `<https://geoconnex.ca/data/catchment/HYF/WSCSSSDA/NRCAN/02OJ*AB>`, a document is returned with data. Except, nowhere in this document this DIR URI is present. It does not exist in that document. If the document is an hypermedia, it is likely to use its own URI or API call to refer to itself and other elements. In the best-case scenario, the document will have a reference to the NIR. In other words, dereferencing a /data/ does not return a document about that /data/ 
Alistair proposed to use a blank node (an anonymous resource) and an explicit URI/API to get the document and remove the /data/ as a named resource because the /data/ is not a real thing and make it explicit that the NIR *is* the resource of interest, not the /data/. 

This model as several interesting features:

- This model is closer to VoID as it provide explicit data access (https://www.w3.org/TR/void/#access) 
- The blank node prevents the creating of a named node for something that is only local to the MIR (the /data/ resource is not guaranteed to be persistent anyway)
- It does not forbid the /data/ pattern – we can still use it (to unify heterogenous data sources and access methods from non compliant/standard source), it just prevent confusing /data/ with a NIR.

@abhritchie : Did I get the issue right ?

**Comment by abhritchie** [comment]
```json
{
    "@id": "https://lab.scinfo.org.nz/selfie/data/aquifersystem/richelieu",
    "@type": "foaf:Document",
    "url": "https://lab.scinfo.org.nz/selfie/datamcdataface/aquifersystem/richelieu",
    "foaf:primaryTopic": "gw:GW_AquiferSystem",
    "format": [
        "text/turtle",
        "application/ld+json",
        "application/vnd.geo+json",
        "text/html",
        "application/pdf"
    ],
    "conformsTo": "https://www.opengis.net/def/gwml2",
    "provider": "https://opengeospatial.github.io/SELFIE/"
},
{
    "url": "https://lab.scinfo.org.nz/selfie/data/aquifersystem/richelieu",
    "@type": "foaf:Document",
    "foaf:primaryTopic": "gw:GW_AquiferSystem",
    "format": [
        "text/ttl",
        "application/ld+json"
    ],
    "conformsTo": "https://www.opengis.net/def/gwml2",
    "provider": "https://opengeospatial.github.io/SELFIE/"
}
``

**Comment by abhritchie** [comment]
NRCan examples: https://github.com/NRCan/GSIP/tree/master/docs/examples

**Comment by brodaric** [comment]
I think the second option has promise as a compromise solution.  Thoughts?
- it is simpler, neutral about the resource (data id vs api), supports the narrative, and allows (I think) the more compact data encoding favored by AR. On the downside, its less descriptive, but the enhanced description is likely needed for a small group of uses cases.
{
    "url": "https://lab.scinfo.org.nz/selfie/datamcdataface/aquifersystem/richelieu",
    "@type": "foaf:Document",
     ...

**Comment by abhritchie** [comment]
Thanks @brodaric . Let's run with this. I realize this is taking it a bit further, but for SELFIE (very broad context) only the url is needed. The @type value is effectively a constant but data providers that need the narrative clarity are free to provide it. We are working in the open world and providers can add whatever they need to. SELFIE defines a minimum useful set, it is doesn't take a restrictive approach.

**Comment by abhritchie** [comment]
WRT to using foaf:primaryTopic instead of dc:type. [primaryTopic](http://xmlns.com/foaf/spec/#term_primaryTopic) relates to a broader set - all Things, individuals and classes - than we want which is just the class/type of the thing. [type](http://purl.org/dc/elements/1.1/type) is closer to that, and is consistent with our use of [format](http://purl.org/dc/elements/1.1/format). The type definition explicitly says use format for media types.

**Comment by brodaric** [comment]
I think primaryTopic is more appropriate: dc:type is similar to rdf:type - in this case it refers to the type of the resource, which we already specified as a document (foaf:document).  primaryTopic refers to the contents inside the document, which is the intention, e.g. the document is about an aquifer.

**Comment by bsimons14** [comment]
This is way above my brain-space, but Simon Cox's comments about errors in my examples included:
"... incorrect use of rdf:type vs dct:type and dct:conformsTo ..."
I gather it relates to the discussion at https://github.com/w3c/dxwg/issues/314

**Comment by abhritchie** [comment]
To move this IE ahead I'm going to use my privilege as Technical Lead to close this issue with the recommendation that we adopt Boyan's compromise proposal from 26 days ago. If necessary the discussion can be reopened once we have created and used compliant (in the loosest possible sense) instance documents.

**Comment by brodaric** [comment]
Bruce – would be good to get details on any  comments re: our MR encoding

----------------------------
Boyan Brodaric
Research Scientist
Geological Survey of Canada
Natural Resources Canada
117 – 601 Booth St. Ottawa, ON K1A 0E8
Tel: 613-513-8723
Email:  boyan.brodaric@canada.ca<mailto:boyan.brodaric@canada.ca>
