### ISSUE TITLE
SELFIE Show and Tell Sessions

### ISSUE THREAD

**Issue by abhritchie** [opengeospatial/SELFIE#4]
Organise presentations by groups undertaking work that likely offers models the IE can implement:

1. ESIP science-on-schema.org

**Comment by dblodgett-usgs** [comment]
You are on!

**Comment by sgrellet** [comment]
I uploaded the slides I presented today on SELFIE G.Drive: https://drive.google.com/open?id=1XZnbSwa0W29jafdn29JUeC2l9J1bsywr

**Comment by dblodgett-usgs** [comment]
Thanks Sylvain! I'm going to close this issue based on an email I will share with the main SELFIE list right now.
