### ISSUE TITLE
OGC-API Features Implementation Details

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#46]
This issue addresses some details of implementing the NIR/MR pattern in pyGeoAPI raised by @alpha-beta-soup in #21. 

Example doc:
```
{
  "@context": [
    "https://geojson.org/geojson-ld/geojson-context.jsonld",
    "https://opengeospatial.github.io/ELFIE/json-ld/elf.jsonld",
    {
      "vocab": "https://domain.com/vocab#",
      "datetime": "https://pending.schema.org/observationDate",
      "stn_id": "vocab:stn_id",
      "value": "vocab:value"
    }
  ],
  "type": "Feature",
  "id": "http://172.19.0.2:5000/collections/obs/items/371",
  "geometry": {
    "type": "Point",
    "coordinates": [
      -75,
      45
    ]
  },
  "properties": {
    "stn_id": "35",
    "datetime": "2001-10-30T14:24:55Z",
    "value": "89.9"
  }
}
``` 

Question 1) What to put in the id field? Local ID or... ?  
Question 2) How to link back to the collection?
Question 3) How to handle pagination?

**Comment by dblodgett-usgs** [comment]
Q1) Shouldn't it be `@id` and point to an NIR URI?
Q2) I don't think we strictly need to link back to the collection since the client will have come from a collection and/or have the link already and should leave that out of scope for SELFIE.
Q3) Wouldn't it be valid to just add more `@id` blocks and sets of statements to the JSON-LD to support pagination? The MR document shouldn't really care about what "page" it is and it's just a set of triples about the `@id`ed thing.

**Comment by alpha-beta-soup** [comment]
I think perhaps I wasn't being very clear, and confused the matter for question 3 by talking about something (the feature collection) without providing an example or ontext. I probably should have used a more informal channel than Github. Further, really I haven't yet got to the point of implementing MIRs, rather I'm still just providing equivalent "IR" representations of the OGC Features API response objects with structured/linked data, in the hope that it a PR will be considered for inclusion back upstream into pygeoapi.

Once I've achieved that initial goal, and familiarised myself with pygeoapi, I'll be in a better position to consider MIRs and NIRs as well.

**Comment by dblodgett-usgs** [comment]
Now problem at all. Should we close this issue till you've done a bit more?

**Comment by dblodgett-usgs** [comment]
Closing as not relevant.
