### ISSUE TITLE
SELFIE contexts to be migrated to the ELFIE github.io page.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#50]
We need to decide what portions of the SELFIE contexts should be migrated to the ELFIE github.io

(most of them?) (none of them?)

Need to be careful about them looking too prescriptive.

**Comment by abhritchie** [comment]
Is it OK to just merge the SELFIE contexts with the ones created for ELFIE @dblodgett-usgs ?

Note that I'll also keep the SELFIE contexts intact for participants that are using them for their demos. The ELFIE ones will be the authoritative (in a strongly suggestive rather than sternly prescriptive kind of way) contexts.

**Comment by amacleod-cerdi** [comment]
@abhritchie  I’m sure this is a dumb question. How do I incorporate the work that Abdel @afeliachi  has been doing for the GSMLB/GWML2 minimal ontology into our contexts? I can see .ttl files in the GeoSciML repo but no .jsonld, is this just a conversion process?

https://raw.githubusercontent.com/opengeospatial/GeoSciML/master/ontology/minimal/gwml2_minimal.ttl

**Comment by abhritchie** [comment]
We'll need to create missing context (.jsonld) file.

There is the start of a GSMLB one already in GitHub: SELFIE/docs/contexts/gsmlb_classes_associations_context.json). Looks good, just needs to be renamed gsmlb.jsonld.

We'll need to sort out something for GWML2.

**Comment by dblodgett-usgs** [comment]
@abhritchie -- I would prefer to create _new_ files at different paths that contain the merged contexts. Links to the old contexts should be marked deprecated, but they should be left along for the purpose of posterity and stability of the old ELFIE content.

**Comment by abhritchie** [comment]
OK @dblodgett-usgs. I'll set up ELFIE/docs/json-ld to be versioned:
- ELFIE/docs/json-ld/1/ or ELFIE/docs/json-ld/elfie-1/
- ELFIE/docs/json-ld/2/ or ELFIE/docs/json-ld/elfie-2/

To keep links in existing examples intact we'd need to leave the current files where they are. This is messy (inconsistent).

It would be very easy to update the docs in the repo to point at the right context, but it would break demos hosted elsewhere (e.g. my ELFIE services). Not a big deal to update them, would it upset others? Thoughts?

**Comment by abhritchie** [comment]
We should tag the ELFIE repo ('elfie-1') too.

Can we have a github.io URL for a given release? (https://opengeospatial.github.io/ELFIE/1/?).

**Comment by dblodgett-usgs** [comment]
I prefer the messy option. Could we add a ELFIE/docs/contexts/ and just use that for future stuff? Or rename the new ones and put them in the same place?

Probably making a bigger deal out of not messing with the old stuff but the more permanent those demos can be the better IMHO.

**Comment by abhritchie** [comment]
That's a good plan. I'm excited to be a part of it.

jsonld stays as is, ELFIE/docs/contexts will come into existence as a versioned folder. Small amount of duplication, large amount of clarity.

**Comment by afeliachi** [comment]
@amacleod-cerdi the 3 minimal ontologies and their context are now available: 
- [gsml](https://github.com/opengeospatial/GeoSciML/blob/master/ontology/minimal/gsmlb_minimal.ttl)([conext](https://github.com/opengeospatial/SELFIE/blob/master/docs/contexts/gsmlb_minimal_context.jsonld)), 
- [gwml2 ](https://github.com/opengeospatial/GeoSciML/blob/master/ontology/minimal/gwml2_minimal.ttl)([context](https://github.com/opengeospatial/SELFIE/blob/master/docs/contexts/gwml2_minimal_context.jsonld) )
-  hyf ([pending pull](https://github.com/opengeospatial/HY_Features/pull/274))([context](https://github.com/opengeospatial/SELFIE/blob/master/docs/contexts/hyf_minimal_context.jsonld))

**Comment by amacleod-cerdi** [comment]
@afeliachi  Just looking at the gwml2 context. I think the namespace prefixes need a search/replace.  It has gsmlb instead of gwml2?

**Comment by afeliachi** [comment]
@amacleod-cerdi thanks for noticing. I fixed it

**Comment by dblodgett-usgs** [comment]
see: https://github.com/opengeospatial/ELFIE/pull/221 Work in Progress?

**Comment by dblodgett-usgs** [comment]
Done. All future context changes will happen in the ELFIE repo.
