### ISSUE TITLE
Build example for a CUAHSI HIS observation site 

### ISSUE THREAD

**Issue by Castronova** [opengeospatial/SELFIE#60]
Create a basic example of a CUAHSI HIS observation site encoded using the elf.jsonld and hyf.jsonld contexts. Use the huc12obs example as a reference: https://opengeospatial.github.io/ELFIE/usgs/wqp/huc12obs/WIDNR_WQX-10001221.

**Comment by Castronova** [comment]
So far I have the following json-ld. It fails on https://json-ld.org/playground/ with the following error:

```
jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
```

I'm also getting the same error using the `huc12obs` example (above).  

```
 {
    "@context": [
        "https://opengeospatial.github.io/ELFIE/json-ld/elf.jsonld",
        "https://opengeospatial.github.io/ELFIE/json-ld/hyf.jsonld"
    ],
    "@id": "http://localhost:5000/CocoRaHs/us1masf0004",
    "@type": [
        "http://www.opengeospatial.org/standards/waterml2/hy_features/HY_HydroLocation"
    ],
    "HY_HydroLocationType": "hydrometricStation",
    "description": "BRIGHTON 0.5 W - CocoRaHs - us1masf0004",
    "geo": {
        "@type": "schema.GeoCoordinates",
        "schema.latitude": 42.3496,
        "schema.longitude": -71.1589
    },
    "gsp.hasGeometry": {
        "@type": "gsp:Geometry",
        "gsp:asWKT": "POINT (-71.1589, 42.3496)"
    },
    "name": "BRIGHTON 0.5 W - CocoRaHs"
}
```

**Comment by abhritchie** [comment]
Hey @Castronova . This is odd. I can't replicate this. The huc12obs and your example both work fine for me in the playground.
![image](https://user-images.githubusercontent.com/9596562/66533411-4bf8bb00-eb6f-11e9-9f95-9139711b8828.png)

**Comment by afeliachi** [comment]
Hey @Castronova . It can't replicate it ether. The error talks about "same-origin policy". 
It may be related to your Web browser, try with another one. And btw do you happen to work behind a proxy server? It could be that also.

**Comment by Castronova** [comment]
That's strange. I doesn't work in my Chrome browser, but it works in Safari. Thanks for the help!!
