### ISSUE TITLE
mime-type override cannot be trusted / is unknown with schema:url

### ISSUE THREAD

**Issue by denevers** [opengeospatial/SELFIE#66]
I got the previous description totally wrong.

conneg override is when you want the document in a particular format, but the link in a browser will always ask for HTML.  So when we design a landing page, links in the page will always ask for HTML.  If you want other supported formats, there are ways to force to format over conneg.  it's often f= or using "well known" extension ( ex .pdf)

We did decide in Québec to use f=mime-type, but most resources providers out there were not present at that meeting and don't follow that convention.  Therefore, if we have a representation with more that one format, there is no trusted way to get the format we want (without content negotiation)

for example:

```
 [
      dct:conformsTo <https://www.opengis.net/def/gwml2> ;
      dct:format "application/gml+xml", "application/ld+json", "text/ttl" ;
      schema:provider <https://opengeospatial.github.io/SELFIE/> ;
      schema:url "https://lab.scinfo.org.nz/selfie/data/aquifersystem/richelieu"
    ],
```
this url supports 3 formats, clicking this link inside a browser will ask for HTML preferably, and, usually some other kinds of HTML

Firefox 65 is `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`

so in this case, we can't predict what will happen.

It's the main reason GISP has a /data/ handler (to map GSIP f= conventions to whatever remote server used to override content negotiation)

So, what do we do ?

1. it's out of scope since it's only a convenience (real applications will do proper conneg)
2. we expect HTML page to do conneg (just using the URL is wrong)
3. we forbid multiple mime-type when there is schema:url (they should be modelled as multiple representations)

**Comment by dblodgett-usgs** [comment]
Out of scope IMHO. Should we write anything about this in the ER though?

**Comment by dblodgett-usgs** [comment]
There's been a lot of discussion of this in OGC-API Features and Common. 
See: https://github.com/opengeospatial/oapi_common/issues/28
and: https://github.com/opengeospatial/ogcapi-features/issues/12

In short, I think we don't touch this in SELFIE other than to point out that such practices can be helpful when clicking through html links in linked data landing pages. I would prefer to leave the debate to the Common SWG.

**Comment by dblodgett-usgs** [comment]
I linked this into the ["resource resolution alternatives" ](https://docs.google.com/document/d/1b-TdqWl3jf2jJD7dYvLkxTa6JEGxtUJAue7jSiaEE2s/edit#heading=h.2lz0hbfpz9kk)section of the draft ER. It will also be a thing in the [:SELFIE Functions"](https://docs.google.com/document/d/1b-TdqWl3jf2jJD7dYvLkxTa6JEGxtUJAue7jSiaEE2s/edit#heading=h.hz63j5cpjcy7) section.
