### ISSUE TITLE
Finish list of contexts in ELFIE repository.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#83]
Need to finish this: https://github.com/opengeospatial/ELFIE/blob/master/docs/contexts/elfie-2/readme.md
Contexts themselves also need a little clean up.

- [x] void context formatting
- [x] gsmlb context name 
- [x] schema:about in elf-data
- [x] naming convention for all the files

**Comment by dblodgett-usgs** [comment]
Should we also migrate the geosparql elf-network? 
https://opengeospatial.github.io/ELFIE/json-ld/elf-network.jsonld

**Comment by dblodgett-usgs** [comment]
I'm working through this issue over here: https://github.com/opengeospatial/ELFIE/pull/225/files

Am unsure what the correct formatting for the [void context](https://github.com/opengeospatial/ELFIE/blob/master/docs/contexts/elfie-2/void.jsonld) should be.

Instead of:
```
{
    "@context": {
        "void": "http://rdfs.org/ns/void#",
        "Dataset": {
            "@id": "void:Dataset"
        }
}
```

Should it be like:
```
{
    "@context": {
        "void": "http://rdfs.org/ns/void#",
        "Dataset": "void:Dataset"
}
```
Also, unsure what we meant by the task `schema:about in elf-data`. I think we were just going to drop it, right?

**Comment by dblodgett-usgs** [comment]
One other item -- there are a few other contexts in ELFIE-1. Thinking I will pull them into the ELFIE-2 list to get everything in one place. Any dissent to doing this? sosa, tsml, skos, and soilie are the candidates.

**Comment by abhritchie** [comment]
https://github.com/opengeospatial/SELFIE/issues/83#issuecomment-592257148: yes, second option.

**Comment by alpha-beta-soup** [comment]
Aren't those two options in https://github.com/opengeospatial/SELFIE/issues/83#issuecomment-592257148 identical?

**Comment by abhritchie** [comment]
In terms of how a JSON-LD parser would deal with them: yes.
In terms of style: no.

**Comment by abhritchie** [comment]
Why use a style? Because some user may not (or will refuse to) use JSON-LD tools. A style keeps paths to values consistent.
Always `@context.${key}` not a mix of that or `@context.${key}.@id`.

**Comment by dblodgett-usgs** [comment]
OK -- I think I have this in https://github.com/opengeospatial/ELFIE/pull/226

Will go ahead and merge so we can look at it in the wild: https://opengeospatial.github.io/ELFIE/contexts/elfie-2/
