### ISSUE TITLE
Use cases to include in ER

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/SELFIE#85]
In the [use case section of the draft ER,](https://docs.google.com/document/d/1b-TdqWl3jf2jJD7dYvLkxTa6JEGxtUJAue7jSiaEE2s/edit#bookmark=id.g209006m5k5p) we have:

- NZ Soils Data
- US/Canada Cross Border Linked Data
- EU Surface Water Groundwater Linked Data
- AU Distributed Borehole Data

Are there others that people want to include?

**Comment by jyucsiro** [comment]
A bit late to the party but here's one from the AU Loc-I project (http://loci.cat/). Had to use .zip because .md is not supported.

[SELFIE_usecase_loci.zip](https://github.com/opengeospatial/SELFIE/files/4047482/SELFIE_usecase_loci.zip)

**Comment by dblodgett-usgs** [comment]
🙏 @jyucsiro I've added it here: https://github.com/opengeospatial/SELFIE/blob/master/docs/demo/loci.md

**Comment by dblodgett-usgs** [comment]
At this point, I have the following use cases / experiments in the ER:

Internet of Water  
https://opengeospatial.github.io/SELFIE/demo/internet_of_water

GSIP  
https://opengeospatial.github.io/SELFIE/demo/gsip

scinfo.nz  
Some examples in: https://opengeospatial.github.io/SELFIE/examples/ but no write up.
@abhritchie ?? 
  
CeRDI  
https://opengeospatial.github.io/SELFIE/demo/CeRDI_VVG

BRGM-BLiv  
Some examples in: https://opengeospatial.github.io/SELFIE/examples/ but no write up.
@sgrellet @afeliachi ??

LOCI  
https://opengeospatial.github.io/SELFIE/demo/loci

Template is here: https://github.com/opengeospatial/SELFIE/blob/master/docs/demo/SELFIE_usecase_template.md It shouldn't take more than a couple hours to get worked up.

**Comment by dblodgett-usgs** [comment]
Have worked these into the ER and going to wrap things up as is.
