### ISSUE TITLE
sameAs to include other formats where at least one representation is 'In-Band'

### ISSUE THREAD

**Issue by bsimons14** [opengeospatial/SELFIE#93]
Seeking confirmation on the implementation of the 'In-Band/Out-of-Band' discussion (Issue #88 ).
My take is:
 "sameAs" contains links where the identifier (the "@id") is an identifier of an on-line resource for the Non-Information Resource, AND at least ONE of the representations/formats available from this on-line resource is "In-Band" (see #88 for what that means). Other "Out-Of-Band" representations may be available from the same resource through content negotiation. These are also to be listed under "sameAs".
So at https://geo.org.au/info/well/107972?f=json under "sameAs" CeRDI has the 'In-Band' ld+json representation available, as well as 'Out-Of-Band' gml+xml and html representations:
"sameAs": [
{
"@id": "https://id.cerdi.edu.au/wmis/data/gwml2/borehole/107972",
"@type": "gw:Borehole",
"format": [
"application/ld+json",
"application/gml+xml",
"text/html"
],
"provider": "http://www.water.vic.gov.au"
},

The alternative of placing the 'Out-Of-Band' representations (gml+xml, html) under "subjectOf seems overly complicated.

**Comment by dblodgett-usgs** [comment]
This is my understanding -- yes. Another example would be a geojson representation of the same landing-resource that can give you JSON-LD or HTML.

**Comment by dblodgett-usgs** [comment]
Agreed we could close on the call on 2/25.
