### ISSUE TITLE
query about elf-index context file

### ISSUE THREAD

**Issue by amacleod-cerdi** [opengeospatial/SELFIE#95]
Hey  @abhritchie  can you check the formatting of the context file at 
[https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld](https://opengeospatial.github.io/ELFIE/contexts/elfie-2/elf-index.jsonld)
  
It has 
image: {
    @id: "schema:image",
    @type: "@id"
}
Which doesn't seem right. I've been going through updating our demo to point to the new context locations but the html version in the mediator is choking when attempting to expand this (I think).

**Comment by abhritchie** [comment]
There's a reason. The value of `image` can only ever be a link so I followed JSON-LD recommendations for [type coercion](https://www.w3.org/TR/json-ld/#example-12-type-coercion). But:
1. JSON-LD has a more relaxed attitude to URIs than we do (the whole URI-14/`@id`/URL-200/`url` debacle) means coercing the type to `@id` is confusing.
2. `image` values are pretty much self-governing - there's no (sensible) option other than to provide a URL to an image.
So ... that's a very long-winded way (I thought you might like an explanation) of saying I'll make it consistent with the other property declarations in the contexts.

**Comment by dblodgett-usgs** [comment]
fixed in https://github.com/opengeospatial/ELFIE/pull/224
