### ISSUE TITLE
Geosparql context/namespace to RDF rather than doc

### ISSUE THREAD

**Issue by jyucsiro** [opengeospatial/SELFIE#96]
Looking at this context (https://opengeospatial.github.io/ELFIE/json-ld/elf.jsonld) 
... and doing some tests, it appears that `http://www.opengeospatial.org/standards/geosparql` is used rather than `http://www.opengis.net/ont/geosparql#`

It would be better to use `http://www.opengis.net/ont/geosparql#` as this can then be used as the namespace to the GeoSPARQL ontology, which can be loaded in a tool chain.

So I'd suggest one change in that context definition shown here:
```
   "gsp": "http://www.opengis.net/ont/geosparql#",
``` 

Maybe this is should be an issue in ELFIE repo?
(also examples need to use the new URLs to the contexts)...

**Comment by sgrellet** [comment]
if would +1 (we use http://www.opengis.net/ont/geosparq in our examples).
But related to issue #67, I remember there was a discussion in November Toulouse TC during the SDWIG session about the pattern to be used within OGC NA (to have a coherence in URI patterns of all ontologies exposed at OGC level). 
@afeliachi may be able to provide more details on this

**Comment by afeliachi** [comment]
yes this was one of the questions raised in Toulouse, the answer wasn't very clear regarding Geosparql, as it is a "real" owl ontology & doesn't conform to the URI scheme of OGC NA. 
But what is sure is that `http://www.opengeospatial.org/standards/geosparql` is not correct URI for the ontology, and that the current one is `http://www.opengis.net/ont/geosparql#`

**Comment by dblodgett-usgs** [comment]
It's been changed in all the contexts.
