### ISSUE TITLE
Update context file to contain updated ssn-ext to sosa namespace

### ISSUE THREAD

**Issue by bsimons14** [opengeospatial/SELFIE#99]
@dr-shorthair wrote #94:
"I just noticed that you are still using the old version of SSN-ext ... because the graph URI https://www.w3.org/ns/ssn/ext/ resolves to a stale version of the RDF :-( It was all updated when the new Working Draft of SSN-ext was published in January. I've logged this issue to get it fixed.

The main difference is for you guys is that the new classes and properties are now in the SOSA namespace and ssn-ext: is no longer used - see https://raw.githubusercontent.com/w3c/sdw/gh-pages/ssn-extensions/rdf/ssn-ext.ttl"

**Comment by dr-shorthair** [comment]
The online version of the ontology is now corrected 
https://github.com/w3c/sdw/issues/1169
see https://www.w3.org/ns/ssn/ext/

**Comment by dblodgett-usgs** [comment]
Sorry to be naive here but are there changes this implies to this context? 
https://opengeospatial.github.io/ELFIE/contexts/elfie-2/ssn-ext.jsonld

**Comment by dr-shorthair** [comment]
There is no `https://www.w3.org/ns/ssn/ext/` namespace or `ssn-ext:` prefix. 
There is a graph at https://www.w3.org/ns/ssn/ext/ which contains some new  axioms and URIs in the https://www.w3.org/ns/sosa/ namespace, but I think that is a secondary concern. It would be required for processing and reasoning, but not to mention the new resources.

**Comment by dblodgett-usgs** [comment]
Shoot -- didn't think this would close like that. @dr-shorthair I just removed the ssn-ext context and added the content from it to https://github.com/dblodgett-usgs/ELFIE/blob/master/docs/contexts/elfie-2/sosa.jsonld

That in line with what you would have expected?

**Comment by dr-shorthair** [comment]
This is the full set:
![image](https://user-images.githubusercontent.com/608303/75504439-95697a00-5a2c-11ea-96e6-c5b43781eb0e.png) 
![image](https://user-images.githubusercontent.com/608303/75504459-a1edd280-5a2c-11ea-9939-946135aa809d.png)

**Comment by dblodgett-usgs** [comment]
The intention of the context was to strike a balance of completeness and approachability. If you feel we've left anything out that should really be in, can you PR against the context? Happy to add if needed.

**Comment by dr-shorthair** [comment]
Apologies @dblodgett-usgs - it was unclear to me whether you wanted your config to automatically accommodate all SOSA. If that is not the case then it is up to you guys to pick and choose. I was only providing this for x-reference. 

(The issue closed automatically because you had the magic word 'fixes' in the PR.)

**Comment by dr-shorthair** [comment]
but to answer @dblodgett-usgs question more clearly - no, I don't expect you to declare classes and properties that you don't use. But it would be best to use the correct namespace for the ones that you do! 

i.e. all the new classes and properties from https://www.w3.org/TR/vocab-ssn-ext/ are in the sosa: namespace.
